### List products
GET http://localhost:3000/products

### Create product
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "Product 1",
  "description": "Product 1 description",
  "price": 500,
  "image_url": "https://via.placeholder.com/400x300"
}

### Get product by id
GET http://localhost:3000/products/831c7ab7-fa49-49a0-a9b3-35d6a0441071


### Login user 1
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "john",
  "password": "john123"
}

### Login user 2
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "Cris",
  "password": "Cris"
}

### List orders
GET http://localhost:3000/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiam9obiIsImlhdCI6MTcwNjgzNjQ2NCwiZXhwIjoxNzA2ODM2NTI0fQ.U2_0dzuK2pKHhJr9PF6YtNXUPI4xbD0Y0Q5UH6Td6tU

### Create order
POST http://localhost:3000/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsInVzZXJuYW1lIjoiY2hyaXMiLCJpYXQiOjE3MDY2NDI0MjYsImV4cCI6MTcwNjY0MjQ4Nn0.ATPshOiL6zF3QQC6ewAxLaRyTxyx2Fo2nkXCadZtMY8
Content-Type: application/json

{
  "items": [
    {
      "product_id": "10c83bae-cf4b-4564-b38a-5c15a4d6f0da",
      "quantity": 1
    },
    {
      "product_id": "2be82129-cf3b-46ab-bd2c-acf7cb13917d",
      "quantity": 2
    }
  ],
  "card_hash": "456"
}

### Get order by id
GET http://localhost:3000/orders/7f35a7e1-a15c-4036-90d9-b150e672b6c1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiam9obiIsImlhdCI6MTcwNjY0MDA5NCwiZXhwIjoxNzA2NjQwMTU0fQ.mIywByT9nxOmoIelCbz6meJmE8SOtwNSnRU0dXLMoNg